- content/authorization/client-credentials-grant.md
> :pencil2: :ok_hand: Fixed typos.

- content/PHP-SDK/_index.md
[MP-79](https://myparcelcombv.atlassian.net/browse/MP-79)
> MP-79 Add new getPickupDropoffLocations behavior to docs

- README.md
- content/api/resources/shipment-statuses.md
- content/api/resources/shipments.md
- content/api/resources/statuses.md
- layouts/partials/custom-head.html
- added google tag manager scripts
- shipment statuses description
> tag manager + shipment statuses

- content/api/create-a-shipment.md
- content/api/resources/shipments.md
**Changes**
- Expanded "create-a-shipment" page.
- Added address object to shipment resource page.
- https://myparcelcombv.atlassian.net/browse/MP-1322
> MP-1322 create a shipment how to

- content/api/resources/common-objects/_index.md
- content/api/resources/common-objects/addresses.md
- content/api/resources/shops.md
- static/css/myparcelcom.css
**Changes**
- Added a "common objects" section within the resources, describing commonly used objects that are not necessarily resources, like addresses and prices
- Improved the shops resource page with expandable request examples, copied from the api spec
- https://myparcelcombv.atlassian.net/browse/MP-1517
> Improve shop resource page

- content/api/_index.md
- content/api/authentication/client-credentials-grant.md
- content/api/create-a-shipment/_index.md
- content/api/resources/shops.md
- content/api/retrieve-carrier-locations.md
- content/api/retrieve-shipment-files.md
- content/api/retrieve-shipment-statuses.md
[MP-1548](https://myparcelcombv.atlassian.net/browse/MP-1548)
> Remove 'v1' from urls.

- content/carrier-integration-program/_index.md
> Changed program to programme

- content/api/authentication/client-credentials-grant.md
Added the full auth url for clarification
Updated bearer token expiry time to the current situation
> Add auth url, fix bearer token expiry

- content/api/resources/regions.md
**Changes**
- Fixed type of name filter from integer to string
- Add info on postal_code filter
https://myparcelcombv.atlassian.net/browse/MP-1683
> Add postal code filter to region resource

- content/api/_index.md
- content/api/create-a-shipment/_index.md
- content/api/retrieve-shipment-files.md
- content/api/retrieve-shipment-statuses.md
**Changes**
- Updated create a shipment page.
- Changed all mentions of api production url to sandbox url.
- [Subtask](https://myparcelcombv.atlassian.net/browse/MP-1750)
- [Story](https://myparcelcombv.atlassian.net/browse/MP-1629)
> MP-1750-update-create-a-shipment-page

- content/api/resources/service-options.md
- content/api/resources/service-rates.md
**Changes**
- Updated service options page to reflect new structure
- Removed non-existing service rate endpoints
- Moved service rate parameter with query params into GET endpoint and added parameter section.
- [MP-1748](https://myparcelcombv.atlassian.net/browse/MP-1748) (Subtask)
- [MP-1629](https://myparcelcombv.atlassian.net/browse/MP-1629) (Story)
> MP-1748 Update service options resource

- content/php-sdk/_index.md
- content/php-sdk/common-use-case.md
- content/php-sdk/price-calculator.md
- content/php-sdk/retrieving-resources.md
**Changes**
- Added service rates to retrieving resources page.
- Removed contracts from retrieving resources page.
- Added service options to retrieving resources page.
- Reordered the retrieving resources page.
- Adjusted price calculator and common use case pages to reflect new shipment structure.
- [MP-1779](https://myparcelcombv.atlassian.net/browse/MP-1779) (Subtask)
- [MP-1617](https://myparcelcombv.atlassian.net/browse/MP-1617) (Story)
> MP-1779 Update SDK pages with new shipment structure.

- content/api/retrieve-shipment-files.md
- content/api/retrieve-shipment-statuses.md
**Changes**
- Updated status overview table on retrieve statuses page.
- [MP-1821](https://myparcelcombv.atlassian.net/browse/MP-1821) (Subtask)
- [MP-1580](https://myparcelcombv.atlassian.net/browse/MP-1580) (Story)
> MP-1821 Updated mentions of status codes to comply to the new proposal.

- content/api/authentication/scopes.md
- content/api/resources/contracts.md
- content/api/resources/service-rates.md
- content/api/resources/services/_index.md
- content/api/resources/shipments/_index.md
- content/api/resources/shops.md
- content/api/retrieve-shipment-files.md
- content/api/retrieve-shipment-statuses.md
**Changes**
- Update scope requirements to the new list of scopes
- https://myparcelcombv.atlassian.net/browse/MP-1863
- https://myparcelcombv.atlassian.net/browse/MP-1687
> Update scope requirements

- content/api/resources/carriers.md
https://myparcelcombv.atlassian.net/browse/MP-1667
> :memo: add code to carrier resource

- content/api/resources/carrier-pudo-locations.md
- content/php-sdk/_index.md
https://myparcelcombv.atlassian.net/browse/MP-1669
> :memo: add categories to carrier pudo resource

- content/api/resources/regions.md
https://myparcelcombv.atlassian.net/browse/MP-1670
> :memo: add category to region resource

- content/php-sdk/advanced-usage.md
- content/php-sdk/connecting-with-the-api.md
**Important**
**Changes**
- Updated docs to reflect Httpclient changes to the SDK
> Update sdk docs for client changes

- content/api/resources/regions.md
- content/php-sdk/retrieving-resources.md
**Changes**
- Updated docs on `getRegions()`
- https://myparcelcombv.atlassian.net/browse/MP-2173
- https://myparcelcombv.atlassian.net/browse/MP-2112
> Update docs on retrieving regions

- content/api/rpc-endpoints.md
- content/api/rpc-endpoints/_index.md
- content/api/rpc-endpoints/suggest-addess.md
[MP-2180](https://myparcelcombv.atlassian.net/browse/MP-2180)
> RPC & Suggest address

- content/api/rpc-endpoints/update-shipment-statuses.md
- https://myparcelcombv.atlassian.net/browse/MP-2224 (subtask)
- https://myparcelcombv.atlassian.net/browse/MP-2147 (story)
> MP-2224 Added page on manually updating a shipment's status.

- content/api/rpc-endpoints/suggest-address.md
- https://myparcelcombv.atlassian.net/browse/MP-2284 (subtask)
- https://myparcelcombv.atlassian.net/browse/MP-2272 (story)
> MP-2284 Updated address_service request body with street_number_suffix.

- content/api/resources/services/_index.md
- Related issue: https://myparcelcombv.atlassian.net/browse/MP-2165
> Add code filter to service

- .circleci/config.yml
- docker/build/Dockerfile
- docker/build/default.conf
- kube/deployment.template.yaml
- kube/service.template.yaml
This makes the docs page available on docs.develop.myparcel.com YEAH
> 🐳 ☸ Dockerized and kubernetized docs

- content/api/resources/shipments/_index.md
- https://myparcelcombv.atlassian.net/browse/MP-2322 (subtask) 
- https://myparcelcombv.atlassian.net/browse/MP-2195 (story)
> MP-2322 Added documentation on the channel attribute in shipments 

- .circleci/config.yml
- kube/service.template.yaml
https://myparcelcombv.atlassian.net/browse/MP-2074
> :green_heart: deploy master to staging

- content/api/rpc-endpoints/suggest-address.md
- Related issue: https://myparcelcombv.atlassian.net/browse/MP-2324
> Update address suggest to reflect limited attributes

- content/api/resources/hooks/logs.md
- content/api/resources/hooks/trigger.md
- content/api/resources/shipments/_index.md
- Related issue: https://myparcelcombv.atlassian.net/browse/MP-2388
> Add hook log resource

- content/api/retrieve-shipment-statuses.md
- https://myparcelcombv.atlassian.net/browse/MP-2371
> MP-2371 Added information on shipment-processing status.

- content/api/resources/services/_index.md
- [Subtask: MP-2479](https://myparcelcombv.atlassian.net/browse/MP-2479)
- [Story: MP-2411](https://myparcelcombv.atlassian.net/browse/MP-2411)
> MP-2479 Added uses_volumetric_weight to the resource page of services.

- content/api/resources/shipments/_index.md
- content/api/resources/shipments/physical-properties.md
- [MP-2456](https://myparcelcombv.atlassian.net/browse/MP-2456) (Subtask)
- [MP-2409](https://myparcelcombv.atlassian.net/browse/MP-2409) (Story)
> MP-2456 Volumetric weight in Shipments resource page.

- content/api/resources/services/_index.md
- content/api/resources/services/address-rule.md
- content/api/resources/services/address-rules.md
- Related issue: https://myparcelcombv.atlassian.net/browse/MP-2531
> Added warning on deprecating relation

- content/api/resources/service-rates.md
- [MP-2558](https://myparcelcombv.atlassian.net/browse/MP-2558) (Subtask)
- [MP-2500](https://myparcelcombv.atlassian.net/browse/MP-2500) (Story)
> MP-2558 Volumetric weight filter documentation

- content/api/resources/shipments/_index.md
- [Subtask](https://myparcelcombv.atlassian.net/browse/MP-2573)
- [Story](https://myparcelcombv.atlassian.net/browse/MP-2306)
> MP-2573 Added total_value to shipment resource page.

- content/api/resources/carriers.md
- content/api/resources/contracts.md
- content/api/resources/files.md
- content/api/resources/services/_index.md
- content/api/resources/shipments/_index.md
- [Subtask](https://myparcelcombv.atlassian.net/browse/MP-2603)
- [Story](https://myparcelcombv.atlassian.net/browse/MP-2559)
> Added documentation on mime-types.

- content/api/create-a-webhook/_index.md
- content/api/resources/hooks/action.md
- content/api/resources/hooks/trigger.md
- content/api/using-hooks.md
- related issue: https://myparcelcombv.atlassian.net/browse/MP-2599
> Add webhook docs

- content/api/resources/service-rates.md
- [Subtask](https://myparcelcombv.atlassian.net/browse/MP-2695)
- [Story](https://myparcelcombv.atlassian.net/browse/MP-2655)
> MP-2695 Added has_active_contract filter to service rate filters.

- content/api/retrieve-shipment-files.md
https://myparcelcombv.atlassian.net/browse/MP-2702
> 📝 MP-2702 mention webhook and polling on shipment files page

- content/api/create-a-shipment/add-liability-coverage.md
- content/api/create-a-shipment/carrier-specific-requirements.md
- content/api/resources/contracts.md
- content/api/resources/liability-coverages.md
- [Story](https://myparcelcombv.atlassian.net/browse/MP-1866)
> MP-1866 Liability coverage

- content/api/resources/hooks/action.md
- [Subtask](https://myparcelcombv.atlassian.net/browse/MP-2975)
- [Story](https://myparcelcombv.atlassian.net/browse/MP-2862)
> MP-2975 Added a section on hook value converters.

- content/api/create-a-shipment/_index.md
- [Task](https://myparcelcombv.atlassian.net/browse/MP-2973)
> MP-2973 Creating shipments with service-code.

- content/api/resources/common-objects/addresses.md
- Related issue: https://myparcelcombv.atlassian.net/browse/MP-2869
> Remove postal code requirement

- content/api/retrieve-shipment-statuses.md
- content/api/rpc-endpoints/update-shipment-statuses.md
- content/api/rpc-endpoints/void-shipment.md
- https://myparcelcombv.atlassian.net/browse/MP-3099
> MP-3099 Voiding shipments

- content/api/resources/shipments/_index.md
- [Subtask](https://myparcelcombv.atlassian.net/browse/MP-3214)
- [Story](https://myparcelcombv.atlassian.net/browse/MP-3155)
> MP-3214 Added docs on a shipment's customer reference field.

- content/php-sdk/common-use-case.md
The current example resulted in a shipment without a contract.
> 📝 Improve SDK shipment example

- content/api/resources/hooks/trigger.md
- content/api/resources/shipments/_index.md
- content/api/using-hooks.md
- Subtask: https://myparcelcombv.atlassian.net/browse/MP-3514
- Story: https://myparcelcombv.atlassian.net/browse/MP-3390
> MP-3514 Shipment tags

- content/_index.md
- content/api/_index.md
- content/api/authentication/client-credentials-grant.md
- content/api/create-a-shipment/_index.md
- content/api/create-a-shipment/add-liability-coverage.md
- content/api/create-a-shipment/carrier-specific-requirements.md
- content/api/create-a-webhook/_index.md
- content/api/resources/files.md
- content/api/resources/hooks/action.md
- content/api/resources/hooks/logs.md
- content/api/resources/liability-coverages.md
- content/api/resources/services/_index.md
- content/api/resources/shipments/physical-properties/volumetric-weight.md
- content/api/retrieve-carrier-locations.md
- content/api/retrieve-shipment-statuses.md
- content/api/using-hooks.md
- content/delivery-plugin/_index.md
- content/development/_index.md
- content/development/docker.md
- content/php-sdk/_index.md
- content/php-sdk/advanced-usage.md
- content/php-sdk/common-use-case.md
- content/php-sdk/price-calculator.md
- content/php-sdk/retrieving-resources.md
- Fixed typo's and punctuation.
- Changed default page size to 100.
> ✏️ Fixed typo's and punctuation

- content/api/resources/hooks/action.md
Added documentation about HMAC SHA-256 and added examples on how to verify requests on php and JavaScript.,
> 🚑 📝 Explain about hmac

- content/api/resources/hooks/action.md
Added documentation about HMAC SHA-256 and added examples on how to verify requests on php and JavaScript.,
> 📝 Explain about hmac

- content/api/resources/shipments/_index.md
- content/api/resources/shipments/items.md
https://myparcelcombv.atlassian.net/browse/MP-3668
> ✨ Added image_url to shipment item

- content/api/rpc-endpoints/suggest-address.md
- Removed the warning about supported country codes for suggest address RPC endpoint
> Removed warning about available country codes

- content/api/resources/files.md
- content/api/resources/reports.md
https://myparcelcombv.atlassian.net/browse/MP-3761
> MP-3761 ✨ Reports resource page

- content/api/resources/shipments/_index.md
- content/api/resources/shipments/customs.md
- Subtask: https://myparcelcombv.atlassian.net/browse/MP-3926
- Story: https://myparcelcombv.atlassian.net/browse/MP-3773
> MP-3926 Added docs on shipping value

- content/api/resources/hooks/action.md
- content/api/resources/hooks/logs.md
- content/api/resources/hooks/trigger.md
- content/api/using-hooks.md
https://myparcelcombv.atlassian.net/browse/MP-3869
> 📝 Hook logs

- content/api/create-a-webhook/_index.md
- content/api/resources/hooks/action.md
- https://myparcelcombv.atlassian.net/browse/MP-3831
> MP-3831 Added documentation on webhook retry feature.

- .circleci/config.yml
- kube/deployment.template.yaml
Using AWS ECR instead of Docker Cloud images
Using AWS ECR instead of Docker Cloud images
> Using AWS ECR instead of Docker Cloud images
> 🐳 Using AWS ECR instead of Docker Cloud images

- content/api/create-a-webhook/_index.md
- content/api/resources/hooks/action.md
- content/api/resources/hooks/logs.md
- content/api/resources/hooks/trigger.md
- content/api/resources/shipment-statuses.md
- content/api/retrieve-shipment-statuses.md
https://myparcelcombv.atlassian.net/browse/MP-4082
Specify the usage of hook triggers.
https://myparcelcombv.atlassian.net/browse/MP-4136
Update shipment statuses and carrier statuses.
> MP-4082 MP-4136 📝 Hook triggers and Shipment statuses

- content/e-commerce-integration-program/_index.md
- Fixed diagram title text to describe the figures
- Added more context on diagram flow steps
> 📝 e-Commerce Integration Programme fixes

- content/api/create-a-shipment/carrier-specific-requirements.md
We got asked questions about carrier length limitations. I have updated the page where we listed some carrier specific requirements. It is not a complete list yet, but it's a start.
> 📝 More carrier length limitations

- content/api/resources/service-options.md
- Added `values_format` property to the list of Service Option attributes.
- https://myparcelcombv.atlassian.net/browse/MP-4345
> MP- 4345 Service option values_format
